myproject/apps/article/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from . import views, list_views

app_name = 'article'
urlpatterns = [
    path('article-column/', views.article_column.as_view(), name='article_column'),
    path('rename-column/', views.rename_article_column.as_view(), name='rename_article_column'),
    path('del-column/', views.del_article_column.as_view(), name='del_article_column'),
    path('article-post/', views.article_post.as_view(), name='article_post'),
    path('article-list/', views.article_list.as_view(), name='article_list'),
    path('article/<int:id>/<slug:slug>', views.article_detail.as_view(), name='article_detail'),
    path('del-article/', views.del_article.as_view(), name='del_article'),
    path('edit-article/<int:article_id>', views.edit_article.as_view(), name='edit_article'),
    path('list-article-titles/', list_views.article_titles.as_view(), name='article_titles'),
    path('article-content/<int:id>/<slug:slug>', list_views.article_detail.as_view(), name='article_content'),
    path('list-article-titles/<username>/', list_views.article_titles.as_view(), name='author_articles'),
    path('like-article/', list_views.like_article.as_view(), name='like_article'),
    path('article-tag/', views.article_tag.as_view(), name='article_tag'),
    path('del-article-tag', views.del_article_tag.as_view(), name='del_article_tag'),
]

myproject/myproject/urls.py
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from article import list_views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', article_views.article_titles.as_view(), name='index'),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/apps/article/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from slugify import slugify
from account.models import User

# Create your models here.
class ArticleColumn(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='article_column')
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column

class ArticleTag(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tag')
    tag = models.CharField(max_length=500)

    def __str__(self):
        return self.tag

class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="article")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, on_delete=models.CASCADE, related_name="article_column")
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    user_like = models.ManyToManyField(User, related_name='articles_like', blank=True)
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag', blank=True)

    class Meta:
        ordering = ("title",)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)

    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id, self.slug])

    def get_url_path(self):
        return reverse('article:article_content', args=[self.id, self.slug])

class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, on_delete=models.CASCADE, related_name='comments')
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_time', )

    def __str__(self):
        return 'Comment by {0} on {1}'.format(self.commentator.username, self.article)

myproject/apps/article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost, Comment, ArticleTag


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column', )

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'body')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('commentator', 'body')

class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ('tag', )

myproject/apps/article/views.py
import json
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import ArticleColumn, ArticlePost, ArticleTag
from .forms import ArticleColumnForm, ArticlePostForm, ArticleTagForm

# Create your views here.

class article_column(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request):
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, 'article/column/article_column.html', {'columns': columns, 'column_form': column_form})

    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request):
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse('0')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse('1')

class rename_article_column(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request):
        column_name = request.POST['column_name']
        column_id = request.POST['column_id']
        try:
            line = ArticleColumn.objects.get(id=column_id)
            line.column = column_name
            line.save()
            return HttpResponse('1')
        except:
            return HttpResponse('0')

class del_article_column(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request):
        column_id = request.POST['column_id']
        try:
            line = ArticleColumn.objects.get(id=column_id)
            line.delete()
            return HttpResponse('1')
        except:
            return HttpResponse('0')

class article_post(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request):
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        article_tags = request.user.tag.all()
        return render(request, 'article/column/article_post.html',
                      {'article_post_form': article_post_form, 'article_columns': article_columns,
                       'article_tags': article_tags})

    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request):
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                tags = request.POST['tags']
                if tags:
                    for atag in json.loads(tags):
                        tag = request.user.tag.get(tag=atag)
                        new_article.article_tag.add(tag)
                return HttpResponse('1')
            except:
                return HttpResponse('0')
        else:
            return HttpResponse('-1')

class article_list(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request):
        article_list = ArticlePost.objects.filter(author=request.user)
        paginator = Paginator(article_list, 8)
        page = request.GET.get('page')
        try:
            current_page = paginator.page(page)
            articles = current_page.object_list
        except PageNotAnInteger:
            current_page = paginator.page(1)
            articles = current_page.object_list
        except EmptyPage:
            current_page = paginator.page(paginator.num_pages)
            articles = current_page.object_list
        return render(request, 'article/column/article_list.html', {'articles': articles, 'page': current_page})

class article_detail(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request, id, slug):
        article = get_object_or_404(ArticlePost, id=id, slug=slug)
        return render(request, 'article/column/article_detail.html', {'article': article})

class del_article(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request):
        article_id = request.POST['article_id']
        try:
            article = ArticlePost.objects.get(id=article_id)
            article.delete()
            return HttpResponse('1')
        except:
            return HttpResponse('0')

class edit_article(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request, article_id):
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={'title': article.title})
        this_article_column = article.column
        return render(request, 'article/column/edit_article.html', {
            'article': article,
            'article_column': article_column,
            'this_article_form': this_article_form,
            'this_article_column': this_article_column,
            'article_columns': article_columns,
        })

    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request, article_id):
        edit_article = ArticlePost.objects.get(id=article_id)
        try:
            edit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            edit_article.title = request.POST['title']
            edit_article.body = request.POST['body']
            edit_article.save()
            return HttpResponse('1')
        except:
            return HttpResponse('0')

class article_tag(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request):
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request, 'article/tag/tag_list.html',
                      {'article_tags': article_tags, 'article_tag_form': article_tag_form})

    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request):
        tag_post_form = ArticleTagForm(request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse('1')
            except:
                return HttpResponse('0')
        else:
            return HttpResponse('-1')

class del_article_tag(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request):
        tag_id = request.POST['tag_id']
        try:
            tag = ArticleTag.objects.get(id=tag_id)
            tag.delete()
            return HttpResponse('1')
        except:
            return HttpResponse('-1')

myproject/templates/article/tag/tag_list.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>article tags</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/5.10.0-12/css/all.min.css">
</head>

<body style="width: 100%;">
{% include "header.html" %}

<div class="row" style="width: 100%">
    <div class="col-md-2 offset-1" >
        {% include 'article/leftslider.html' %}
    </div>
    <div class="col-md-8" >
        <div>
            <h3>添加文章标签</h3>
            <form class="form-horizontal" action="." method="post">{% csrf_token %}
                <div style="margin: 15px 0;">
                    <span style="margin-right: 5px;">文章标签</span>{{ article_tag_form.tag }}
                    <input type="button" class="btn btn-primary" value="添加" onclick="add_tag()">
                </div>
            </form>
        </div>
        <hr/>
        <div>
            <h3>已有标签列表</h3>
            <table class="table table-hover">
                <tr>
                    <td>序号</td>
                    <td>文章标签</td>
                    <td>操作</td>
                </tr>
                {% for article_tag in article_tags %}
                    <tr id={{ forloop.counter }}>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ article_tag.tag }}</td>
                        <td>
                            <a href="javascript:" onclick="del_tag(this, {{ article_tag.id }})">
                                <i style="color: black" class="fa fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                {% empty %}
                    <p>You have no article tags. Please add them.</p>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% include "footer.html" %}
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src='{% static "layer/layer.js" %}'></script>
<script type="text/javascript">
    function add_tag(){
        tag = $("#id_tag").val();
        $.ajax({
            url: '{% url "article:article_tag" %}',
            type: "POST",
            data: {"tag":tag, csrfmiddlewaretoken:'{{ csrf_token }}'},
            success: function(e){
                if(e=="1"){
                    layer.msg("添加成功。");
                    window.location.reload();
                } else if(e=='-1') {
                    layer.msg('请核对信息。')
                } else{
                    layer.msg('系统错误，请联系管理员。')
                }
            }
        });
    }

    function del_tag(the, tag_id){
        var article_tag = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除文章标签",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除文章标签《'+article_tag+'》</p> </div>',
            btn:['确定', '取消'],
            yes: function(){
                $.ajax({
                    url: '{% url "article:del_article_tag" %}',
                    type:"POST",
                    data: {"tag_id":tag_id, csrfmiddlewaretoken: '{{ csrf_token }}'},
                    success: function(e){
                        if(e=="1"){
                            parent.location.reload();
                            layer.msg("已删除。");
                        }else{
                            layer.msg("删除失败，请联系管理员。");
                        }
                    },
                })
            },
        });
    }
</script>
</body>
</html>