myproject/apps/account/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),
    path('register/', views.registerView.as_view(), name='register'),
    path('password-change/', auth_views.PasswordChangeView.as_view(
            template_name='account/password_change_form.html'
            , success_url='/account/password-change-done/'
    ), name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html')
         , name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='account/password_reset_form.html',
        email_template_name='account/password_reset_email.html',
        success_url='/account/password-reset-done',
    ), name='password_reset'),
    path('password-reset-done', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password_reset_confirm.html',
        success_url='/account/password-reset-complete/'
    ), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name='password_reset_complete'),
    path('my-info/', views.my_info.as_view(), name='my_info'),
    path('change-info/', views.change_my_info.as_view(), name='change_my_info'),
    path('my-avatar/', views.my_avatar.as_view(), name='my_avatar'),
]

myproject/apps/article/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from . import views, list_views

app_name = 'article'
urlpatterns = [
    path('article-column/', views.article_column.as_view(), name='article_column'),
    path('rename-column/', views.rename_article_column.as_view(), name='rename_article_column'),
    path('del-column/', views.del_article_column.as_view(), name='del_article_column'),
    path('article-post/', views.article_post.as_view(), name='article_post'),
    path('article-list/', views.article_list.as_view(), name='article_list'),
    path('article/<int:id>/<slug:slug>', views.article_detail.as_view(), name='article_detail'),
    path('del-article/', views.del_article.as_view(), name='del_article'),
    path('edit-article/<int:article_id>', views.edit_article.as_view(), name='edit_article'),
    path('list-article-titles/', list_views.article_titles.as_view(), name='article_titles'),
    path('article-content/<int:id>/<slug:slug>', list_views.article_detail.as_view(), name='article_content'),
    path('list-article-titles/<username>/', list_views.article_titles.as_view(), name='author_articles'),
    path('like-article/', list_views.like_article.as_view(), name='like_article'),
    path('article-tag/', views.article_tag.as_view(), name='article_tag'),
    path('del-article-tag', views.del_article_tag.as_view(), name='del_article_tag'),
]

myproject/myproject/urls.py
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from article import list_views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', article_views.article_titles.as_view(), name='index'),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body style="width: 100%;">
{% include "header.html" %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
{% include "footer.html" %}
<script src="{% static 'js/jquery-3.4.1.min.js' %}"> </script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'layer/layer.js' %}"></script>
</body>
</html>

myproject/templates/footer.html
<div> <hr>
    <p class="text-center">copy right www.zooter.com</p>
</div>

myproject/templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-light navbar-light">
    <a class="navbar-brand" href="{% url 'index' %}"><img width="50px" src="{% static 'image/Avatar.jpg' %}" /></a>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">BLOG</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto" style="padding-right: 60px;">
        {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" data-toggle="dropdown">{{ user.username }}</a>
                <div class="dropdown-menu" style="min-width: 4rem;max-width: 8rem">
                    <a class="dropdown-item" href="{% url 'account:my_info' %}">我的信息</a>
                    <a class="dropdown-item" href="{% url 'article:article_column' %}">后台管理</a>
                    <a class="dropdown-item" href="{% url 'account:password_change' %}">修改密码</a>
                    <a class="dropdown-item" href="{% url 'account:logout' %}">Sign out</a>
                </div>
            </li>
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="{% url 'account:logout' %}">Sign out</a>#}
{#            </li>#}
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account:login' %}">Sign in</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account:register' %}">Sign up</a>
            </li>
        {% endif %}
    </ul>
</nav>

myproject/templates/paginator.html
<div class="pagination">
    <span class="step-links"></span>
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">&nbsp;Page {{ page.number }} of {{ page.paginator.num_pages }}&nbsp;
    </span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
</div>