myproject/apps/article/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from . import views, list_views

app_name = 'article'
urlpatterns = [
    path('article-column/', views.article_column.as_view(), name='article_column'),
    path('rename-column/', views.rename_article_column.as_view(), name='rename_article_column'),
    path('del-column/', views.del_article_column.as_view(), name='del_article_column'),
    path('article-post/', views.article_post.as_view(), name='article_post'),
    path('article-list/', views.article_list.as_view(), name='article_list'),
    path('article/<int:id>/<slug:slug>', views.article_detail.as_view(), name='article_detail'),
    path('del-article/', views.del_article.as_view(), name='del_article'),
    path('edit-article/<int:article_id>', views.edit_article.as_view(), name='edit_article'),
    path('list-article-titles/', list_views.article_titles.as_view(), name='article_titles'),
    path('article-content/<int:id>/<slug:slug>', list_views.article_detail.as_view(), name='article_content'),
    path('list-article-titles/<username>/', list_views.article_titles.as_view(), name='author_articles'),
    path('like-article/', list_views.like_article.as_view(), name='like_article'),
    path('article-tag/', views.article_tag.as_view(), name='article_tag'),
    path('del-article-tag', views.del_article_tag.as_view(), name='del_article_tag'),
]

myproject/myproject/urls.py
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from article import list_views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', article_views.article_titles.as_view(), name='index'),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/apps/article/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from slugify import slugify
from account.models import User

# Create your models here.
class ArticleColumn(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='article_column')
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column

class ArticleTag(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tag')
    tag = models.CharField(max_length=500)

    def __str__(self):
        return self.tag

class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="article")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, on_delete=models.CASCADE, related_name="article_column")
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    user_like = models.ManyToManyField(User, related_name='articles_like', blank=True)
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag', blank=True)

    class Meta:
        ordering = ("title",)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)

    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id, self.slug])

    def get_url_path(self):
        return reverse('article:article_content', args=[self.id, self.slug])

class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, on_delete=models.CASCADE, related_name='comments')
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_time', )

    def __str__(self):
        return 'Comment by {0} on {1}'.format(self.commentator.username, self.article)

myproject/apps/article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost, Comment, ArticleTag


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column', )

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'body')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('commentator', 'body')

class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ('tag', )

myproject/apps/article/views.py
import json
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import ArticleColumn, ArticlePost, ArticleTag
from .forms import ArticleColumnForm, ArticlePostForm, ArticleTagForm

# Create your views here.

class article_column(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request):
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, 'article/column/article_column.html', {'columns': columns, 'column_form': column_form})

    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request):
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse('0')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse('1')

class rename_article_column(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request):
        column_name = request.POST['column_name']
        column_id = request.POST['column_id']
        try:
            line = ArticleColumn.objects.get(id=column_id)
            line.column = column_name
            line.save()
            return HttpResponse('1')
        except:
            return HttpResponse('0')

class del_article_column(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request):
        column_id = request.POST['column_id']
        try:
            line = ArticleColumn.objects.get(id=column_id)
            line.delete()
            return HttpResponse('1')
        except:
            return HttpResponse('0')

class article_post(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request):
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        article_tags = request.user.tag.all()
        return render(request, 'article/column/article_post.html',
                      {'article_post_form': article_post_form, 'article_columns': article_columns,
                       'article_tags': article_tags})

    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request):
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                tags = request.POST['tags']
                if tags:
                    for atag in json.loads(tags):
                        tag = request.user.tag.get(tag=atag)
                        new_article.article_tag.add(tag)
                return HttpResponse('1')
            except:
                return HttpResponse('0')
        else:
            return HttpResponse('-1')

class article_list(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request):
        article_list = ArticlePost.objects.filter(author=request.user)
        paginator = Paginator(article_list, 8)
        page = request.GET.get('page')
        try:
            current_page = paginator.page(page)
            articles = current_page.object_list
        except PageNotAnInteger:
            current_page = paginator.page(1)
            articles = current_page.object_list
        except EmptyPage:
            current_page = paginator.page(paginator.num_pages)
            articles = current_page.object_list
        return render(request, 'article/column/article_list.html', {'articles': articles, 'page': current_page})

class article_detail(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request, id, slug):
        article = get_object_or_404(ArticlePost, id=id, slug=slug)
        return render(request, 'article/column/article_detail.html', {'article': article})

class del_article(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request):
        article_id = request.POST['article_id']
        try:
            article = ArticlePost.objects.get(id=article_id)
            article.delete()
            return HttpResponse('1')
        except:
            return HttpResponse('0')

class edit_article(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request, article_id):
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={'title': article.title})
        this_article_column = article.column
        return render(request, 'article/column/edit_article.html', {
            'article': article,
            'article_column': article_column,
            'this_article_form': this_article_form,
            'this_article_column': this_article_column,
            'article_columns': article_columns,
        })

    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request, article_id):
        edit_article = ArticlePost.objects.get(id=article_id)
        try:
            edit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            edit_article.title = request.POST['title']
            edit_article.body = request.POST['body']
            edit_article.save()
            return HttpResponse('1')
        except:
            return HttpResponse('0')

class article_tag(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request):
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request, 'article/tag/tag_list.html',
                      {'article_tags': article_tags, 'article_tag_form': article_tag_form})

    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request):
        tag_post_form = ArticleTagForm(request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse('1')
            except:
                return HttpResponse('0')
        else:
            return HttpResponse('-1')

class del_article_tag(View):
    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request):
        tag_id = request.POST['tag_id']
        try:
            tag = ArticleTag.objects.get(id=tag_id)
            tag.delete()
            return HttpResponse('1')
        except:
            return HttpResponse('-1')

myproject/templates/article/list/article_content.html
{% load static %}
{% load article_tags %}
{% with total_likes=article.user_like.count users_like=article.user_like.all %}

    <!DOCTYPE html>
    <html lang="zh-cn">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>article content</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}">
        <link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/5.10.0-12/css/all.min.css">
    </head>

    <body style="width: 100%;">
    {% include "header.html" %}
    <div class="container" style="width: 100%">
        <div class="row">
            <div class="col-md-9">
                <h1>{{ article.title }}</h1>
                <p><a href="{% url 'article:author_articles' article.author.username %}">{{ article.author.username }}</a></p>
                <div>
                    <span>{{ total_likes }} like{{ total_likes | pluralize }}<i class="fa fa-thumbs-up" style="margin-left:5px;color: black"></i></span>
                    <span>{{ total_views }} view{{ total_views | pluralize }}</span>
                </div>
                <div>
                    <p><span><strong>Tags:&nbsp</strong></span>{{ article.article_tag.all | join:', ' }}</p>
                </div>
                <div id="editormd-view">
                    {{ article.body | markdown }}
                </div>
            </div>
            <div class="col-md-3">
                <div>
                    <h3>最受欢迎的文章</h3>
                    <ol>
                        {% for article_rank in most_viewed %}
                            <li>
                                <a href="{{ article_rank.get_url_path }}">{{ article_rank.title }}</a>
                            </li>
                        {% endfor %}
                    </ol>
                </div>
                <hr/>
                <div>
                    <h3>最新的文章</h3>
                    {% latest_articles 4 %}
                </div>
                <hr/>
                <div>
                    <h3>最多评论的文章</h3>
                    {% most_commented_articles as most_comments %}
                    <ol>
                        {% for comment_article in  most_comments %}
                            <li>
                                <a href="{{ comment_article.get_url_path }}">{{ comment_article.title }}</a>
                            </li>
                        {% endfor %}
                    </ol>
                </div>
            <hr/>
            <div>
                <h3>相似推荐文章</h3>
                {% for similar in similar_articles %}
                <p><a href="{{ similar.get_url_path }}">{{ similar.title }}</a></p>
                {% empty %}
                <p>暂无文章</p>
                {% endfor %}
            </div>
            </div>
        </div>
        <div>
            <p class="text-center">
                {% if user in users_like %}
                    <a href="#" onclick="like_article({{ article.id }}, 'dislike')"><i class="fa fa-thumbs-down" style="color: black;"></i></a>
                {% else %}
                    <a href="#" onclick="like_article({{ article.id }}, 'like')"><i class="fa fa-thumbs-up" style="color: black;"></i></a>
                {% endif %}
            </p>
        </div>
        <div>
            <p class="text-center"><strong>点赞本文的读者</strong></p>
            {% for user in users_like %}
                <p class="text-center">{{ user.username }}</p>
            {% empty %}
                <p class="text-center">还没有人对此文章表态</p>
            {% endfor %}
        </div>
        <div>
            <hr>
            <div>
                <h3>本文有{{ article.comments.count }}评论</h3>
                {% for comment in article.comments.all %}
                    <div>
                        <p><strong>{{ comment.commentator }}</strong>说:</p>
                        <p style="margin-left:40px;">{{ comment.body }}</p>
                    </div>
                {% empty %}
                    <p>没有评论</p>
                {% endfor %}
                <hr>
                <h3></span>看文章，发评论，不要沉默</h3>
                <form action="{% url 'article:article_content' article.id article.slug %}" method="post" class="form-horizontal" role="form">{% csrf_token %}
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">评论员</label>
                        <div class="col-sm-10">
                            {{ comment_form.commentator}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">评论</label>
                        <div class="col-sm-10">
                            {{ comment_form.body }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <p><input type="submit" name="" value=" 发 评 论 " class="btn btn-primary"></p>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>

    {% include "footer.html" %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src='{% static "layer/layer.js" %}'></script>
    <script src='{% static "editor/lib/marked.min.js" %}'></script>
    <script src='{% static "editor/lib/prettify.min.js" %}'></script>
    <script src='{% static "editor/lib/raphael.min.js" %}'></script>
    <script src='{% static "editor/lib/underscore.min.js" %}'></script>
    <script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
    <script src='{% static "editor/lib/flowchart.min.js" %}'></script>
    <script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
    <script src='{% static "editor/editormd.js" %}'></script>
    <script type="text/javascript">
        $(function(){
            editormd.markdownToHTML("editormd-view", {
                htmlDecode: "style, script, iframe",
                emoji:true,
                taskList:true,
                tex:true,
                flowChart:true,
                sequenceDiagram:true,
            });
        });
        function like_article(article_id, action) {
            $.ajax({
                url:"{% url 'article:like_article' %}",
                type:"post",
                data:{csrfmiddlewaretoken:'{{ csrf_token }}', 'id':article_id, 'action':action},
                success: function (e) {
                    if(e=='1'){
                        layer.msg('点赞成功');
                        window.location.reload();
                    }else if(e=='-1'){
                        layer.msg('系统错误，请联系管理员。');
                        location.reload();
                    }else {
                        layer.msg('我会继续努力的');
                        location.reload();
                    }
                }
            });
        }
    </script>
    </body>
    </html>
{% endwith %}

myproject/templates/article/list/article_titles.html
{% extends "base.html" %}
{% load article_tags %}
{% block title %} articles {% endblock %}
{% block content %}
    <div class="row text-center">
        <h1>阅读，丰富头脑，善化行为</h1>
    </div>
    <div class="text-center">
        <p>这里共有{% total_articles %}篇文章</p>
    </div>
    <div class="container">
        {% for article in articles %}
            <div class="list-group" style="margin: 20px;">
                <a href="{{ article.get_url_path }}" class="list-group-item active">
                    <h4 class="list-group-item-heading">{{article.title}}</h4>
                </a>
                <p class="list-group-item-text">作者:<a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a></p>
                <p class="list-group-item-text">概要:{{article.body|slice:'70'| linebreaks}}</p>
            </div>
        {% endfor %}
    </div>
    {% include "paginator.html" %}
{% endblock %}

myproject/templates/article/list/author_articles.html
{% extends "base.html" %}
{% load article_tags %}
{% block title %} author articles {% endblock %}
{% block content %}
    <div class="text-center">
        <h1>{{ user }}的文章</h1>
    </div>
    <div class="text-center">
        <p>{{ user }}共有{% author_article_num user %}篇文章</p>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                {% for article in articles %}
                    <div class="list-group" style="margin: 20px;">
                        <a href="{{ article.get_url_path }}" class="list-group-item active">
                            <h4 class="list-group-item-heading">{{article.title}}</h4>
                        </a>
                        <p class="list-group-item-text">作者:<a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a></p>
                        <p class="list-group-item-text">概要:{{article.body|slice:'70'| linebreaks}}</p>
                    </div>
                {% endfor %}
                {% include "paginator.html" %}
            </div>
            <div class="col-md-4">
                <div style="margin-top: 20px;">
                    <img  src="{{ avatar }}" alt="avatar"/>
                </div>
                <div>
                    <p>{{ user.username }}</p>
                </div>
                {% if userinfo %}
                    <p>{{ userinfo.company }}</p>
                    <p>{{ userinfo.aboutme }}</p>
                {% else %}
                    <p>这个作者太懒，什么都没留下。</p>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

myproject/templates/article/list/latest_articles.html
<ul>
    {% for article in latest_articles %}
    <li>
        <a href="{{ article.get_url_path }}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>